import type { Metadata } from "next";
import { Bona_Nova } from "next/font/google";
import "./globals.css";
import Header from './components/Header';
import Sidebar from "./components/Sidebar";
import { Provider } from "@/components/ui/provider";
import { UserProvider } from "./components/UserContext";

const bonaNovaSC = Bona_Nova({
  weight: '400',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Felagin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <head>
        <link rel="icon" href="mus.png" />
      </head>
      <body className={bonaNovaSC.className}>
        {/* Оборачиваем в UserProvider */}
        <UserProvider>
          <Header />
          <Provider>
            <Sidebar>
              {children}
            </Sidebar>
          </Provider>
        </UserProvider>
      </body>
    </html>
  );
}
