import type { Metadata } from "next";
import { Bona_Nova } from "next/font/google";
import "./globals.css";
import Header from './components/Header';
import Sidebar from "./components/Sidebar";

const bonaNovaSC = Bona_Nova({
  weight: '400',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Felagin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='mus.png' />
      </head>
      <body className={bonaNovaSC.className}>
        <Header/>
        <Sidebar>
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
